// 阻塞host
const GWBlockHosts = [
    'windows.net',
    'wwads',
    'bitwarden',
    'protechts',
    'cedex',
    'phnc',
    'javh',
    'langchain',
    'github.io',
    'steam',
    'v2w.org',
    'v2ray',
    'mangabz',
    'mzstatic',
    'v2fly',
    'webuters',
    'freepik',
    'muse',
    'clarity',
    'neuroflash',
    'nitrocdn',
    'heapanalytics',
    'leonardo',
    'react.dev',
    'chatpdf',
    'discord',
    'pages.dev',
    'blazingly',
    'www.die.net',
    'infoworld',
    'dokumen',
    'ipqualityscore',
    'google',
    'gmail',
    'mixpanel',
    'recaptcha',
    'duckduckgo',
    'auth0.com',
    'msftauth',
    'live.com',
    'microsoftonline',
    'ip138.com',
    'daily.dev',
    'marktechpost',
    'fakeyou.com',
    'arxiv.org',
    'statsigapi',
    'wolframcdn',
    'lorelattice',
    'hellopublic',
    'herokuapp',
    'biztoc',
    'megacourses',
    'cloudinary.com',
    'buysellads.net',
    'ethicalads.io',
    'onesignal.com',
    'unity3d.com',
    'kubernetes.io',
    'trackjs',
    'katacoda.com',
    'steampowered',
    'leetcode.com',
    'tiktok',
    'bit.ly',
    'amzn.to',
    'twitter',
    'youtube',
    'unsplash',
    'wikisource',
    'nr-data',
    'segment',
    'uservoice',
    'localxh',
    'newrelic',
    'aiservices',
    'wise.com',
    'depay',
    'clarity',
    'netspend',
    'bincheck',
    'arkoselabs',
    'curl.haxx.se',
    'funcaptcha',
    'dingxiang-inc.com',
    'huggingface',
    'hk01',
    'mandrillapp',
    'nobepay',
    'tidio',
    'alipayobjects',
    'googletagmanager.com',
    'newrelic.com',
    'linkedin',
    'ucarecdn',
    'algolianet',
    'amplitude',
    'youtu.be',
    'docker',
    'utteranc',
    'optimizely',
    'discourse-cdn',
    'haveibeenpwned',
    'ankiweb',
    'redhat.com',
    'codefresh',
    'redbubble',
    'imgur.com',
    'superuser',
    'coreos.com',
    'talkgo.org',
    'wikipedia',
    'wikileaks',
    'wikimedia',
    'pypi.org',
    'go.dev',
    'godoc.org',
    'swtch',
    'godaddy',
    'namecheap',
    'gophercises',
    'php.net',
    'atlassian',
    'alpinelinux',
    'mysql.com',
    'twitch',
    'babynames',
    'icann.org',
    'rabbitmq.com',
    'xclient',
    'grpc',
    'v2ex',
    'nabble.com',
    'brendangregg',
    'acm',
    'cloudfront.net',
    'gstatic',
    'btloader',
    'criteo',
    'tapad.com',
    'sc-static',
    'cldup',
    'cloudup',
    'vimeo.com',
    'quora',
    'gohugo.io',
    'snapchat',
    'reddit',
    'mitre',
    'redis.io',
    'umbrella.com',
    'bytebytego',
    'doubleclick',
    'how2shout.com',
    'voorp',
    'traffic',
    'adtng',
    'imglnke',
    'gochronicles.com',
    'slideshare',
    'unpkg.com',
    'cove.chat',
    'diygod',
    'allinfa',
    'hub',
    'slidesharecdn',
    'googleapis',
    'dart',
    'dartpad',
    'flutter',
    'asciinema',
    'opensource',
    'openapis',
    'fedorahosted',
    'phncdn',
    'golang',
    'awesome-go',
    'gobyexample',
    'go-zh.org',
    'gopherchina',
    'programming.guide',
    'revved',
    'answerdash',
    'proxifier',
    'appspot.com',
    'amazon',
    'nginx',
    'zeroturnaround',
    'fontawesome',
    'influxdata',
    'fonticons',
    'buysellads',
    'github',
    'prometheus',
    'gitbooks',
    'brew',
    'medium',
    'twimg',
    'highlightjs.org',
    'privoxy.org',
    'haproxy.org',
    'uubyte',
    'prismic.io',
    'mindnode',
    'gemini',
    'hide.me',
    'libreswan',
    'contentstack',
    'yandex',
    'cncf.io',
    'gcr.io',
    'stackexchange',
    'drift.com',
    'yahoo.com',
    'akamaitechnologies.com',
    'elastic.co',
    'symcb',
    'jsfiddle',
    'jshell',
    'stackshare',
    'lintut.com',
    'facebook',
    'mediawiki',
    'datacenterknowledge',
    'addthis',
    'bibblio',
    'gentoo',
    'slack',
    'micro',
    'you.com',
    'fburl.com',
    'fbcdn',
    'bootstrap',
    'expressjs.com',
    'compose.com',
    'readme.io',
    'shareasale',
    'consulting',
    'netperf',
    'bourgon.org',
    'trello',
    'trellocdn',
    'restapitutorial',
    'paypal',
    'polyfill',
    'oracle',
    'sequelpro',
    'stackoverflow.com',
    'sstatic',
    'w3schools.com',
    'sphinx-themes',
    'packagecontrol.io',
    'xdebug.org',
    'cloudinary',
    'disqus',
    'vagrantup.com',
    'hashicorp.com',
    'tsyndicate',
    'segment.com',
    'ahcdn.com',
    'ytimg.com',
    'ruanyifeng.com',
    'wangbase.com',
    'rawgit',
    'postfix',
    'ghettoforge',
    'digitalocean',
    'plesk',
    'vbird',
    'shadowsocks',
    'marketo.net',
    'dropbox.com',
    'ggpht.com',
    'goo.gl',
    'libhunt',
    'pypa',
    'serverfault',
    'grammarly',
    'dnscrypt',
    'wangdoc',
    'labstack',
    'principlesofchaos',
    'programmaticponderings',
    't.co',
    'google-analytics',
    'imgix.net',
    'amazonaws.com',
    'askubuntu.com',
    'googlesyndication.com',
    'notion',
    'gravatar.com',
    'chrome.com',
    'hubspot',
    'turnoff.us',
    'draveness',
    'python.org',
    'mongodb',
    'potatso.com',
    'valuecom.com',
    'techcrunch',
    'gstatic.com',
    'xuesousou',
    'archive.org',
    'vitess',
    'fonts.net',
    'pinimg.com',
    'gov.au',
    'canada',
    'vox.com',
    'karabiner',
    'pixai',
    'adobedtm.com',
    'coupert.com',
    'sentry.io',
    'azureedge',
    'azure.com',
    'azure.net',
    'suno.ai',
    'apple',
    'bbc',
    '6parkbbs',
    'dioco.io',
    'framerusercontent',
    'framerstatic',
    'posthog',
    'jsdelivr',
    'sofiri.com',
    'shenfendaquan',
    'hotdeals'
];

// 腾讯内部Host
const TencentInnerHosts = [
    'woa.com',
    'oa.com',
];

// ChatGPT
const CloudwrapHosts = [
    'jetbrains.com',
    'tubi',
    'featureassets',
    'prodregistryv2',
    'openai',
    'oaistatic',
    'chatgpt',
    'mixpanel',
    'stripe',
    'aitoolsclub',
    'intercom',
    'getsentry',
    'instagram',
    'upwork',
    'x.com',
    'twitter.com',
    'twimg',
    'deepart'
]

// Direct - 不走代理的域名，优先级最高
const NoProxyHosts = [
    'tencent.com'
]

// 代理主机列表
const proxyConfigs = [
    {
        hosts: TencentInnerHosts,
        address: "PROXY 127.0.0.1:12639",
    },
    {
        hosts: CloudwrapHosts,
        address: "SOCKS5 127.0.0.1:10553",
    },
    {
        hosts: GWBlockHosts,
        address: "SOCKS5 127.0.0.1:10443",
    }
];


/**
 * get a appropriate proxy
 *
 * @param url request url
 * @param host request host
 * @returns {*}
 * @constructor
 */
function FindProxyForURL(url, host) {
    // 不走代理
    for (let j = 0; j < NoProxyHosts.length; j++) {
        if (host.indexOf(NoProxyHosts[j]) !== -1) {
            return 'DIRECT'
        }
    }

    // 按需走不同代理
    for (let i = 0; i < proxyConfigs.length; i++) {
        let proxy = proxyConfigs[i]
        for (let j = 0; j < proxy.hosts.length; j++) {
            if (host.indexOf(proxy.hosts[j]) !== -1) {
                // console.log("match: ", proxy.hosts[j])
                return proxy.address
            }
        }
    }

    // 其他情况不走代理
    return 'DIRECT'
}
